# Generated by Django 4.0.4 on 2022-05-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_goalreminding'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('В процесі', 'В процесі'), ('Виконано', 'Виконано'), ('Відхилена', 'Відхилена')], default='В процесі', max_length=50),
        ),
    ]
