# Generated by Django 4.0.4 on 2022-06-05 17:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_subgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalreminding',
            name='time',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.CreateModel(
            name='SubGoalCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.subgoal')),
            ],
        ),
    ]
