# Generated by Django 4.0.4 on 2022-06-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_goal_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgoalcompletion',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
